/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module fulladder_3 (
    input clk,
    input rst,
    input [2:0] in,
    output reg outc,
    output reg outs
  );
  
  
  
  reg sum;
  
  reg cout;
  
  always @* begin
    
    case (in[0+2-:3])
      default: begin
        cout = 1'h0;
        sum = 1'h0;
      end
      3'h0: begin
        cout = 1'h0;
        sum = 1'h0;
      end
      3'h2: begin
        cout = 1'h0;
        sum = 1'h1;
      end
      3'h4: begin
        cout = 1'h0;
        sum = 1'h1;
      end
      3'h6: begin
        cout = 1'h1;
        sum = 1'h0;
      end
      3'h1: begin
        cout = 1'h0;
        sum = 1'h1;
      end
      3'h1: begin
        cout = 1'h0;
        sum = 1'h1;
      end
      3'h3: begin
        cout = 1'h1;
        sum = 1'h0;
      end
      3'h5: begin
        cout = 1'h1;
        sum = 1'h0;
      end
      3'h7: begin
        cout = 1'h1;
        sum = 1'h1;
      end
    endcase
    outc = cout;
    outs = sum;
  end
endmodule
